# Project info
site_name: Betfair Australia Data Scientists
# site_description: 'foobar'
site_author: 'Betfair Data Scientists'
site_url: 'https://betfair-datascientists.github.io'
# site_dir: '../.'
copyright: 'Copyright &copy; 2018'

# Navigation
nav:
    - Resources: 
        External data & dev resources: index.md
    - Third Party Tools: 
        - Bet Angel - ratings automation: thirdPartyTools/betAngelRatingsAutomation.md
        - Bet Angel - tipping automation: thirdPartyTools/betAngelTippingAutomation.md
    - Historic Data: 
        - Downloading the data: historicdata/index.md
    - Betfair Exchange: 
        - Betfair Exchange: 'https://www.betfair.com.au/exchange/plus/'

# Theme settings
theme:
    name: 'material'
    favicon: 'img/BetfairFavicon.ico'
    logo: 'img/BetfairIcon.jpg'
    # custom_dir: 'custom_theme/'
    language: 'en'
    palette:
        primary: 'amber'
        accent: 'light blue'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    feature:
        tabs: true

# extra_css:
#     - css/extra.css

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
        use_pygments: true
        noclasses: true
        # pygments_style: onedark
    - footnotes
    - meta
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde